spring:
  profiles:
    default: local
    group:
      #      local:
      #        - file-default-logging
      #        - file-error-logging
      dev:
        - file-default-logging
        - file-error-logging
        - slack-error-logging
      prod:
        - file-error-logging
        - slack-error-logging
  application:
    name: hhplus-push-service

server:
  servlet:
    context-path: /api
  port: 8085

logging:
  level:
    org:
      web: debug
      hibernate:
        SQL: debug

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      web: debug
      hibernate:
        SQL: debug

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    org:
      web: INFO
      hibernate:
        SQL: INFO
